export const GET_PRODUC = "GET_PRODUC"
export const SET_RANDOM_QUOTE = "SET_RANDOM_QUOTE"
export const FAILED_RANDOM_QUOTE = "FAILED_RANDOM_QUOTE"
export const FAILED_RANDOM_QUOTE = "FAILED_RANDOM_QUOTE"
