export const GET_PRODUCTS = "GET_PRODUCTS"
export const SET_RANDOM_QUOTE = "SET_RANDOM_QUOTE"
export const FAILED_RANDOM_QUOTE = "FAILED_RANDOM_QUOTE"
export const FAILED_RANDOM_QUOTE = "FAILED_RANDOM_QUOTE"
