export const GET_PRODUCS = "GET_PRODUCS"
export const SET_RANDOM_QUOTE = "SET_RANDOM_QUOTE"
export const FAILED_RANDOM_QUOTE = "FAILED_RANDOM_QUOTE"
export const FAILED_RANDOM_QUOTE = "FAILED_RANDOM_QUOTE"
